pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello from Webhook trigger pipeline'
                echo 'Triggered by GitHub webhook!'
            }
        }
    }
}
